run:
  deadline: 5m

linters:
  enable:
    # - exhaustivestruct (too exhaustive)
    # - gci
    # - godot (too nit picking)
    # - ireturn  (we like when function returns interface)
    # - varnamelen  (we can handle this in code review step)
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/gammazero/deque      ## needed for queue implementation
            - github.com/stretchr             ## needed for test helpers
        test:
          files:
            - "$test"
          allow:
            - $gostd
            - github.com/stretchr
            - github.com/vladopajic/go-actor
  forbidigo:
      forbid:
        - 'time\.Sleep*(# Do not sleep)?'
        - 'panic*(# Do not panic)?'
        - 'os\.Exit*(# Do not exit)?'
        - p: ^fmt\.Print*$
          msg: Do not commit print statements.
  gomoddirectives:
    retract-allow-no-explanation: true
  maintidx:
    under: 40
  misspell:
    locale: US
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 96
    tab-width: 1
  nlreturn:
    block-size: 5
  goimports:
    local-prefixes: github.com/vladopajic/go-actor
  wsl:
    enforce-err-cuddling: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen        ## Function length is okay due to many tests cases
        - wrapcheck     ## No need to check wrapping errors in tests

    - path: export_test\.go
      linters:
        - revive      ## Disabling linter because we intentionally want to use unexported types in tests
