# Config file for go-test-coverage github action.
# go-actor commits to keep 100% test coverage.

profile: cover.out
github-action-output: true
local-prefix: "github.com/vladopajic/go-actor"
threshold:
  file: 100
  package: 100
  total: 100
