# (mandatory) Path to coverprofile file (output of `go test -coverprofile` command)
profile: cover.out

# (optional) When specified reported file paths will not contain local prefix in the output
localPrefix: "github.com/vladopajic/actor"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0) The minimum coverage that each file should have
  file: 94

  # (optional; default 0) The minimum coverage that each package should have
  package: 95

  # (optional; default 50) The minimum total coverage project should have
  total: 95
