name: Code check

on: [push]

permissions:
  contents: read
  pull-requests: read

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.18

            - name: Run tests
              run: go test ./... -v

            - name: Go lint
              uses: golangci/golangci-lint-action@v2
              with:
                version: v1.46.2
                only-new-issues: true
                skip-go-installation: true
                skip-pkg-cache: true
                skip-build-cache: true
