name: test synctest
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  synctest:
    name: synctest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version: 1.27
    
      - name: replace go version
        run: sed -i 's/go 1.22/go 1.27/g' go.mod

      - name: test
        run: |
          go test -tags "synctest" -run Synctest$ -timeout=10s -race -count=10 -shuffle=on -failfast -v ./...
